# Generated by Django 4.2 on 2023-04-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizquestion_delete_question_delete_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
