# Generated by Django 4.2 on 2023-04-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_alter_quizquestion_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestion',
            new_name='DjangoQuizQuestion',
        ),
        migrations.AlterModelOptions(
            name='djangoquizquestion',
            options={},
        ),
    ]
